### ISSUE TITLE
Error when creating database

### ISSUE THREAD

**Issue by stephanvierkant** [bpolaszek/doctrine-native-enums#2]
Thanks for creating and sharing this repo! 

I'm trying this on Symfony 5.4 with PHP 8.1. While the application seems to work, I've got problems in my test suite. This is what I get:

```

In MySQLPlatform.php line 1177:
                                                                                                           
  str_replace(): Argument #3 ($subject) must be of type array|string, App\Model\Enum\DocumentStatus given  
                                                                                                          
```

It's the `\Doctrine\DBAL\Platforms\MySQLPlatform::quoteStringLiteral` method.

Any idea how we can fix this?

**Comment by bpolaszek** [comment]
Hi @stephanvierkant, thanks for reaching out!

After a few tests, I didn't manage to reproduce your issue, and I have no clue where this could come from.
It looks like your `doctrine/dbal` version is 3.1+, although this bundle was tested with `~2.13`. 
But I just ran a sample app test suite with the 3.1.4 version and it passed seamlessly. I'll update the CI here.

Would you mind providing me a minimalist repo where I could reproduce your issue?

Thanks,
Ben

**Comment by stephanvierkant** [comment]
Thanks! I'll try to create a test case.

**Comment by stephanvierkant** [comment]
Looks like a caching problem, sorry! `rm var/cache/* -rf` fixed my problem.
